# coding=utf-8

TICKET_TYPE = [u'监控工单', u'报障工单', u'服务申请', u'变更工单', u'软件发布', u'CMDB变更', u'BPM']
FILL_UNIT = [
    {'unit_name': u'标题', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'所属应用系统', 'unit_attribute': 'drop', 'unit_choices_list':
        []},
    {'unit_name': u'服务目录', 'unit_attribute': 'drop', 'unit_choices_list':
        [u'操作系统维护', u'数据修改', u'明细数据提取', u'数据统计', u'办公维护', u'网络维护', u'测试环境', u'应用咨询', u'安全运维',
         u'基础设施', u'监控支持', u'系统及数据库', u'硬件服务']},
    {'unit_name': u'关键词', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'报障来源', 'unit_attribute': 'drop', 'unit_choices_list': [u'电话', u'微信', u'监控', u'工单', u'其他']},
    {'unit_name': u'故障开始时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'故障描述', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'评审意见说明', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'简介', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'影响程度', 'unit_attribute': 'drop', 'unit_choices_list':
        [u'无影响', u'一般(10%以下用户)', u'严重(30%以上用户)', u'非常严重(50%以上用户)']},
    {'unit_name': u'优先级', 'unit_attribute': 'drop', 'unit_choices_list': [u'低', u'普通', u'高', u'非常高']},
    {'unit_name': u'紧急程度', 'unit_attribute': 'drop', 'unit_choices_list': [u'一般', u'紧急', u'特别紧急']},
    {'unit_name': u'事件根源', 'unit_attribute': 'drop', 'unit_choices_list':
        [u'运维支持', u'网络故障', u'业务咨询', u'第三方故障', u'变更发布导致', u'设备故障', u'业务功能缺失', u'操作失误', u'程序缺陷']},
    {'unit_name': u'事件分类', 'unit_attribute': 'drop', 'unit_choices_list':
        [u'应用系统', u'业务功能', u'程序缺陷', u'操作失误', u'网络', u'存储', u'主机']},
    {'unit_name': u'产生原因', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'解决方案', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'故障结束时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'事件经理评价', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'总体满意度', 'unit_attribute': 'radio', 'unit_choices_list': [u'非常满意', u'满意', u'一般', u'不满意']},
    {'unit_name': u'响应及时性', 'unit_attribute': 'star', 'unit_choices_list': []},
    {'unit_name': u'处理及时性', 'unit_attribute': 'star', 'unit_choices_list': []},
    {'unit_name': u'服务态度', 'unit_attribute': 'star', 'unit_choices_list': []},
    {'unit_name': u'您的意见及建议', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'所属应用系统', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'类型', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'监控来源', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'大类', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'子类', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'状态', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'地址', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'告警组', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'编码', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'首次发生时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'末次发生时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'摘要', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'是否可用性事件', 'unit_attribute': 'radio', 'unit_choices_list': [u'是', u'否']},
    {'unit_name': u'申请描述', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'验收方案', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'建议处理人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'建议验收人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'指定处理人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'建议验证人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'版本类型', 'unit_attribute': 'drop', 'unit_choices_list': [u'常规', u'紧急', u'项目']},
    {'unit_name': u'版本号', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'重要级别', 'unit_attribute': 'drop', 'unit_choices_list': [u'1级', u'2级', u'3级', u'4级', u'5级']},
    {'unit_name': u'项目需求编号', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'简介', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'验收人', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'系统名称', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'是否配套修改上线', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'上线单号', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'项目负责人', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'应用相关', 'unit_attribute': 'check', 'unit_choices_list':
        [u'对现有系统服务有影响', u'对上下游系统服务有影响', u'应用可回滚到上线前状态', u'应用不可回滚', u'环境可回滚', u'环境不可回滚',
         u'数据可回滚', u'数据不可回滚', u'有标准软件上线脚本', u'无标准软件上线脚本', u'难以回滚，影响范围|', u'业务中断时间（分钟）|',
         u'其他|']},
    {'unit_name': u'系统、数据库相关', 'unit_attribute': 'check', 'unit_choices_list':
        [u'不涉及系统环境、数据库等配置的调整', u'涉及系统环境、数据库等配置的调整，变更编号为|']},
    {'unit_name': u'网络相关', 'unit_attribute': 'check', 'unit_choices_list':
        [u'不涉及网络相关配置的调整', u'涉及网络相关配置的调整，变更编号为|']},
    {'unit_name': u'数据影响性分析相关', 'unit_attribute': 'check', 'unit_choices_list':
        [u'机构调整', u'用户调整', u'科目调整', u'表结构调整', u'数据字典/代码表调整', u'无数据调整']},
    {'unit_name': u'安全相关', 'unit_attribute': 'check', 'unit_choices_list':
        [u'不涉及应用、网络等安全配置的调整', u'涉及应用、网络等安全配置的调整，变更编号为|']},
    {'unit_name': u'灾备相关', 'unit_attribute': 'check', 'unit_choices_list':
        [u'不涉及灾备配置的调整', u'涉及灾备配置的调整，变更编号为|']},
    {'unit_name': u'网点终端相关', 'unit_attribute': 'check', 'unit_choices_list':
        [u'不涉终端相关配置的调整', u'涉及终端相关配置的调整，变更编号为|']},
    {'unit_name': u'项目组相关', 'unit_attribute': 'check', 'unit_choices_list': [u'代码审查']},
    {'unit_name': u'ip地址', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'开始时间', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'结束时间', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'计划上线时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'计划上线结束时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'其他上线要求', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'实施人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'复核人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'验证人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'验证方案', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'验证说明', 'unit_attribute': 'check', 'unit_choices_list':
        [u'上线窗口期业务验证', u'次日业务验证', u'无业务验证', u'有回滚，难以验证']},
    {'unit_name': u'评审日期', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'发布时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'选择执行人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'执行人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'执行开始时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'执行结束时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'执行评价', 'unit_attribute': 'drop', 'unit_choices_list': [u'正常', u'待改进']},
    {'unit_name': u'执行结果', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'执行复核人', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'复核时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'复核说明', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'异常情况', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'回滚操作', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'验证情况', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'验证评价', 'unit_attribute': 'radio', 'unit_choices_list': [u'正常', u'失败', u'取消']},
    {'unit_name': u'关闭时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'关闭人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'备注', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'上线类型', 'unit_attribute': 'drop', 'unit_choices_list': [u'新建系统', u'系统改造']},
    {'unit_name': u'申请人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'申请部门', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'申请时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'一级分类', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'二级分类', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'三级分类', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'变更内容', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'变更时间要求', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'变更方案', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'回退方案', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'验证方案', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'验证结果判断', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'影响及风险分析', 'unit_attribute': 'radio', 'unit_choices_list':
        [u'变更影响对象较重要', u'技术方案首次使用', u'影响监控数据', u'变更影响面较大', u'回退存在困难']},
    {'unit_name': u'变更级别', 'unit_attribute': 'drop', 'unit_choices_list': [u'一般变更', u'重要变更']},
    {'unit_name': u'影响应用系统', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'评估说明', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'执行组', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'维护期开始时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'维护期结束时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'是否紧急变更', 'unit_attribute': 'radio', 'unit_choices_list': [u'是', u'否']},
    {'unit_name': u'计划执行开始时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'计划执行结束时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'执行时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'审批人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'审批意见', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'回退补救措施', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'标准变更执行情况', 'unit_attribute': 'textarea', 'unit_choices_list': []},
    {'unit_name': u'是否涉及配置项修改', 'unit_attribute': 'radio', 'unit_choices_list': [u'是', u'否']},
    {'unit_name': u'处理反馈', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'监控IP', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'设备类型', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'名称', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'操作系统版本', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'短信负责人', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'管理员', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'监控需求', 'unit_attribute': 'table', 'unit_choices_list': []},
    {'unit_name': u'发布人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'延迟时间', 'unit_attribute': 'date', 'unit_choices_list': []},
    {'unit_name': u'延迟原因', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'审核人', 'unit_attribute': 'drop', 'unit_choices_list': []},
    {'unit_name': u'审核意见', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'验证人备注', 'unit_attribute': 'text', 'unit_choices_list': []},
    {'unit_name': u'配置文件内容', 'unit_attribute': 'textarea', 'unit_choices_list': []},
]
NODE_STATUS = [
    {'ticket_type': 2, 'name': u'创建', 'combination': [1, 2, 4, 5, 6, 7], 'status': 'create', 'is_fallback': False},
    {'ticket_type': 2, 'name': u'服务台受理', 'combination': [8], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 2, 'name': u'一级处理', 'combination': [9, 10, 11, 12, 15, 16, 17, 39, 42], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 2, 'name': u'二级处理', 'combination': [9, 10, 11, 12, 15, 16, 17, 39, 42], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 2, 'name': u'科技部领导审批', 'combination': [8, 41], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 2, 'name': u'指定人处理', 'combination': [9, 10, 11, 12, 13, 14, 15, 16, 17], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 2, 'name': u'事件经理回顾', 'combination': [18], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 2, 'name': u'用户回访', 'combination': [19, 20, 21, 22, 23], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 2, 'name': u'结束', 'combination': [], 'status': 'finish', 'is_fallback': False},
    {'ticket_type': 6, 'name': u'创建', 'combination': [], 'status': 'create', 'is_fallback': False},
    {'ticket_type': 6, 'name': u'审批', 'combination': [], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 6, 'name': u'结束', 'combination': [], 'status': 'finish', 'is_fallback': False},
    {'ticket_type': 1, 'name': u'创建', 'combination': [1, 2, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
     'status': 'create', 'is_fallback': False},
    {'ticket_type': 1, 'name': u'一线处理', 'combination': [10, 11, 12, 5, 13, 14, 15, 16, 17, 36, 39, 42],
     'status': 'doing', 'is_fallback': False},
    {'ticket_type': 1, 'name': u'二线处理', 'combination': [10, 11, 12, 5, 13, 14, 15, 16, 17, 36, 39, 42],
     'status': 'doing', 'is_fallback': False},
    {'ticket_type': 1, 'name': u'科技部领导审批', 'combination': [8, 41], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 1, 'name': u'指定人处理', 'combination': [10, 11, 12, 5, 13, 14, 15, 16, 17, 36], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 1, 'name': u'事件经理回顾', 'combination': [18], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 1, 'name': u'结束', 'combination': [], 'status': 'finish', 'is_fallback': False},
    {'ticket_type': 3, 'name': u'创建', 'combination': [1, 2, 4, 37], 'status': 'create', 'is_fallback': False},
    {'ticket_type': 3, 'name': u'服务台受理', 'combination': [8, 41], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 3, 'name': u'处理人处理', 'combination': [12, 10, 16, 38, 39, 40], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 3, 'name': u'科技部领导审批', 'combination': [8, 41], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 3, 'name': u'指定人处理', 'combination': [12, 10, 16, 38], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 3, 'name': u'用户回访', 'combination': [19, 20, 21, 22, 23], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 3, 'name': u'结束', 'combination': [], 'status': 'finish', 'is_fallback': False},
    {'ticket_type': 5, 'name': u'创建', 'combination':
        [1, 90, 2, 45, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], 'status': 'create', 'is_fallback': False},
    {'ticket_type': 5, 'name': u'各组确认可以进行变更', 'combination':
        [61, 62, 63, 111, 112, 66, 67, 68, 69, 70, 71], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 5, 'name': u'评审会意见', 'combination': [72, 8, 73, 74], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 5, 'name': u'执行发布', 'combination': [76, 77, 78, 79], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 5, 'name': u'执行复核', 'combination': [82, 83, 84], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 5, 'name': u'执行验证', 'combination': [85, 86, 87, 88], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 5, 'name': u'结束', 'combination': [], 'status': 'finish', 'is_fallback': False},
    {'ticket_type': 4, 'name': u'创建', 'combination': [1, 2, 97, 98], 'status': 'create', 'is_fallback': False},
    {'ticket_type': 4, 'name': u'变更方案填写', 'combination':
        [99, 100, 101, 102, 103, 104, 105, 106, 107, 67, 68, 108, 109, 110, 111, 112], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 4, 'name': u'执行时间设定', 'combination': [75, 113, 76, 77], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 4, 'name': u'审批时间', 'combination': [114, 115], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 4, 'name': u'审批方案', 'combination': [14, 115], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 4, 'name': u'发布执行', 'combination':
        [76, 77, 78, 79, 116, 117, 118, 133, 119, 120, 121, 122, 123, 124, 125, 126], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 4, 'name': u'发布延迟', 'combination': [127, 128, 129], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 4, 'name': u'发布审核', 'combination': [130, 131], 'status': 'doing', 'is_fallback': True},
    {'ticket_type': 4, 'name': u'发布验证', 'combination': [69, 132], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 4, 'name': u'结束', 'combination': [], 'status': 'finish', 'is_fallback': False},
    {'ticket_type': 7, 'name': u'创建', 'combination': [], 'status': 'create', 'is_fallback': False},
    {'ticket_type': 7, 'name': u'审批', 'combination': [], 'status': 'doing', 'is_fallback': False},
    {'ticket_type': 7, 'name': u'结束', 'combination': [], 'status': 'finish', 'is_fallback': False},

]
FLOW_EDGE = [
    {'ticket_type': 2, 'start_node': 1, 'end_node': 2},
    {'ticket_type': 2, 'start_node': 2, 'end_node': 3},
    {'ticket_type': 2, 'start_node': 2, 'end_node': 5},
    {'ticket_type': 2, 'start_node': 3, 'end_node': 4},
    {'ticket_type': 2, 'start_node': 3, 'end_node': 5},
    {'ticket_type': 2, 'start_node': 3, 'end_node': 7},
    {'ticket_type': 2, 'start_node': 4, 'end_node': 5},
    {'ticket_type': 2, 'start_node': 4, 'end_node': 7},
    {'ticket_type': 2, 'start_node': 5, 'end_node': 6},
    {'ticket_type': 2, 'start_node': 6, 'end_node': 7},
    {'ticket_type': 2, 'start_node': 7, 'end_node': 8},
    {'ticket_type': 2, 'start_node': 7, 'end_node': 9},
    {'ticket_type': 2, 'start_node': 8, 'end_node': 9},
    {'ticket_type': 6, 'start_node': 10, 'end_node': 11},
    {'ticket_type': 6, 'start_node': 11, 'end_node': 12},
    {'ticket_type': 1, 'start_node': 13, 'end_node': 14},
    {'ticket_type': 1, 'start_node': 14, 'end_node': 15},
    {'ticket_type': 1, 'start_node': 14, 'end_node': 16},
    {'ticket_type': 1, 'start_node': 14, 'end_node': 18},
    {'ticket_type': 1, 'start_node': 15, 'end_node': 16},
    {'ticket_type': 1, 'start_node': 15, 'end_node': 18},
    {'ticket_type': 1, 'start_node': 16, 'end_node': 17},
    {'ticket_type': 1, 'start_node': 17, 'end_node': 18},
    {'ticket_type': 1, 'start_node': 18, 'end_node': 19},
    {'ticket_type': 3, 'start_node': 20, 'end_node': 21},
    {'ticket_type': 3, 'start_node': 21, 'end_node': 22},
    {'ticket_type': 3, 'start_node': 21, 'end_node': 23},
    {'ticket_type': 3, 'start_node': 22, 'end_node': 25},
    {'ticket_type': 3, 'start_node': 23, 'end_node': 24},
    {'ticket_type': 3, 'start_node': 24, 'end_node': 25},
    {'ticket_type': 3, 'start_node': 25, 'end_node': 26},
    {'ticket_type': 5, 'start_node': 27, 'end_node': 28},
    {'ticket_type': 5, 'start_node': 28, 'end_node': 29},
    {'ticket_type': 5, 'start_node': 29, 'end_node': 30},
    {'ticket_type': 5, 'start_node': 29, 'end_node': 33},
    {'ticket_type': 5, 'start_node': 30, 'end_node': 31},
    {'ticket_type': 5, 'start_node': 31, 'end_node': 32},
    {'ticket_type': 5, 'start_node': 32, 'end_node': 33},
    {'ticket_type': 4, 'start_node': 34, 'end_node': 35},
    {'ticket_type': 4, 'start_node': 35, 'end_node': 38},
    {'ticket_type': 4, 'start_node': 38, 'end_node': 36},
    {'ticket_type': 4, 'start_node': 38, 'end_node': 43},
    {'ticket_type': 4, 'start_node': 36, 'end_node': 37},
    {'ticket_type': 4, 'start_node': 37, 'end_node': 39},
    {'ticket_type': 4, 'start_node': 39, 'end_node': 40},
    {'ticket_type': 4, 'start_node': 39, 'end_node': 41},
    {'ticket_type': 4, 'start_node': 40, 'end_node': 36},
    {'ticket_type': 4, 'start_node': 41, 'end_node': 42},
    {'ticket_type': 4, 'start_node': 42, 'end_node': 43},
    {'ticket_type': 7, 'start_node': 44, 'end_node': 45},
    {'ticket_type': 7, 'start_node': 45, 'end_node': 46},

]
