# coding=utf-8

from django.utils.translation import ugettext as _

REAL_TIME_INTERVAL = 10
LB_TYPE_CHOICE = ["loadbalancer",
                  "listener",
                  "member"]
SORT_METHOD = ["increase",
               "decrease"]

PERIOD_CHOICE = ["addition_time_data",
                 "real_time_data",
                 "six_hour_data",
                 "one_day_data",
                 "two_week_data",
                 "one_month_data"]

ITEM_CHOICE = ["CPU_USAGE",
               "MEMORY_USAGE",
               "NET_IN",
               "NET_OUT",
               "NET_PKTS_IN",
               "NET_PKTS_OUT",
               "SYS_DISK_READ",
               "SYS_DISK_WRITE",
               # "SYS_DISK_USAGE",
               "SYS_DISK_THROUGHPUT_READ",
               "SYS_DISK_THROUGHPUT_WRITE",
               "DATA_DISK_READ",
               "DATA_DISK_WRITE",
               # "DATA_DISK_USAGE",
               "DATA_DISK_THROUGHPUT_READ",
               "DATA_DISK_THROUGHPUT_WRITE",
               "ROUTER_IN",
               "ROUTER_OUT",
               "PUBLIC_IP_IN",
               "PUBLIC_IP_OUT",
               "PUBLIC_IP_PKTS_IN",
               "PUBLIC_IP_PKTS_OUT",
               "RDS_CPU",
               "RDS_MEMORY",
               "RDS_VOLUME",
               "RDS_IOPS_READ",
               "RDS_IOPS_WRITE",
               "RDS_QPS",
               "RDS_TPS",
               "RDS_ACTIVE_CONN",
               "RDS_CURRENT_CONN",
               "RDS_QUERY",
               "RDS_COMMIT",
               "RDS_ROLLBACK",
               "RDS_SCANNUM",
               "RDS_FREE_BUFFER",
               "RDS_BUFFER_HITRATIO",
               "LB_BANDWIDTH_IN",
               "LB_BANDWIDTH_OUT",
               "LB_LISTENER_RESPONSE_TIME",
               "LB_LISTENER_CONCURRENT_REQUESTS",
               "LB_LISTENER_RESPONSE_ERRORS",
               "LB_LISTENER_CONCURRENT_CONNECTIONS",
               "LB_LISTENER_1XX",
               "LB_LISTENER_2XX",
               "LB_LISTENER_3XX",
               "LB_LISTENER_4XX",
               "LB_LISTENER_5XX",
               "LB_LISTENER_CUMULATIVE_CONNECTIONS",
               "LB_LISTENER_CUMULATIVE_REQUESTS",
               "LB_MEMBER_CUMULATIVE_CONNECTIONS",
               "LB_MEMBER_RESPONSE_TIME",
               "LB_MEMBER_1XX",
               "LB_MEMBER_2XX",
               "LB_MEMBER_3XX",
               "LB_MEMBER_4XX",
               "LB_MEMBER_5XX"]

item_mapper = {"CPU_USAGE": "cpu_util",
               "MEMORY_USAGE": "memory.usage",
               "NET_IN": "network.incoming.bytes.rate",
               "NET_OUT": "network.outgoing.bytes.rate",
               "NET_PKTS_IN": "network.incoming.packets.rate",
               "NET_PKTS_OUT": "network.outgoing.packets.rate",
               "SYS_DISK_READ": "disk.device.read.requests.rate",
               "SYS_DISK_WRITE": "disk.device.write.requests.rate",
               # "SYS_DISK_USAGE": "disk.device.usage",
               "SYS_DISK_THROUGHPUT_READ": "disk.device.read.bytes.rate",
               "SYS_DISK_THROUGHPUT_WRITE": "disk.device.write.bytes.rate",
               "DATA_DISK_READ": "disk.device.read.requests.rate",
               "DATA_DISK_WRITE": "disk.device.write.requests.rate",
               # "DATA_DISK_USAGE": "disk.device.usage",
               "DATA_DISK_THROUGHPUT_READ": "disk.device.read.bytes.rate",
               "DATA_DISK_THROUGHPUT_WRITE": "disk.device.write.bytes.rate",
               "PUBLIC_IP_IN": "ip_bytes_in_rate",
               "PUBLIC_IP_OUT": "ip_bytes_out_rate",
               "PUBLIC_IP_PKTS_IN": "ip_pkts_in_rate",
               "PUBLIC_IP_PKTS_OUT": "ip_pkts_out_rate",
               "RDS_CPU": "mysql_cpu_util",
               "RDS_MEMORY": "mysql_memory.usage",
               "RDS_VOLUME": "mysql_volume",
               "RDS_IOPS_READ": "mysql_ReadIops",
               "RDS_IOPS_WRITE": "mysql_WriteIops",
               "RDS_QPS": "mysql_QPS",
               "RDS_TPS": "mysql_TPS",
               "RDS_ACTIVE_CONN": "mysql_activeConnectionNum",
               "RDS_CURRENT_CONN": "mysql_currentConnectionNum",
               "RDS_QUERY": "mysql_Queries",
               "RDS_COMMIT": "mysql_transCommit",
               "RDS_ROLLBACK": "mysql_transRollback",
               "RDS_SCANNUM": "mysql_scanNum",
               "RDS_FREE_BUFFER": "mysql_innodbFreeBufferSize",
               "RDS_BUFFER_HITRATIO": "mysql_innodbBufferReadHitratio",
               "LB_BANDWIDTH_IN": "bandwidth_in",
               "LB_BANDWIDTH_OUT": "bandwidth_out",
               "LB_LISTENER_RESPONSE_TIME": "listener_response_time",
               "LB_LISTENER_CONCURRENT_REQUESTS": "listener_concurrent_requests",
               "LB_LISTENER_RESPONSE_ERRORS": "listener_response_errors",
               "LB_LISTENER_CONCURRENT_CONNECTIONS": "listener_concurrent_connections",
               "LB_LISTENER_1XX": "listener_1xx",
               "LB_LISTENER_2XX": "listener_2xx",
               "LB_LISTENER_3XX": "listener_3xx",
               "LB_LISTENER_4XX": "listener_4xx",
               "LB_LISTENER_5XX": "listener_5xx",
               "LB_LISTENER_CUMULATIVE_CONNECTIONS": "listener_cumulative_connections",
               "LB_LISTENER_CUMULATIVE_REQUESTS": "listener_cumulative_requests",
               "LB_MEMBER_CUMULATIVE_CONNECTIONS": "member_cumulative_connections",
               "LB_MEMBER_RESPONSE_TIME": "member_response_time",
               "LB_MEMBER_1XX": "member_1xx",
               "LB_MEMBER_2XX": "member_2xx",
               "LB_MEMBER_3XX": "member_3xx",
               "LB_MEMBER_4XX": "member_4xx",
               "LB_MEMBER_5XX": "member_5xx",
               # "BASE_NET_IN": "",
               # "BASE_NET_OUT": "",
               # "PRIVATE_NET_IN": "",
               # "PRIVATE_NET_OUT": "",
               # "SYS_DISK_READ": "",
               # "SYS_DISK_WRITE": "",
               # "SYS_DISK_USAGE": "",
               # "SYS_DISK_THROUGHPUT_READ": "",
               # "SYS_DISK_THROUGHPUT_WRITE": "",
               # "DATA_DISK_READ": "",
               # "DATA_DISK_WRITE": "",
               # "DATA_DISK_USAGE": "",
               # "DATA_DISK_THROUGHPUT_READ": "",
               # "DATA_DISK_THROUGHPUT_WRITE": "",
               # "ROUTER_IN": "",
               # "ROUTER_OUT": "",
               # "PUBLIC_IP_IN": "",
               # "PUBLIC_IP_OUT": ""
               }

item_reserver_mapper = {
    "cpu_util": "CPU_USAGE",
    "memory.usage": "MEMORY_USAGE",
    "network.incoming.packets.rate": "NET_PKTS_IN",
    "network.outgoing.packets.rate": "NET_PKTS_OUT",
    "network.incoming.bytes.rate": "NET_IN",
    "network.outgoing.bytes.rate": "NET_OUT",
    "disk.device.read.requests.rate": "DISK_READ",
    "disk.device.write.requests.rate": "DISK_WRITE",
    # "disk.device.usage": "DISK_USAGE",
    "disk.device.read.bytes.rate": "DISK_THROUGHPUT_READ",
    "disk.device.write.bytes.rate": "DISK_THROUGHPUT_WRITE",
    "ip_bytes_in_rate": "PUBLIC_IP_IN",
    "ip_bytes_out_rate": "PUBLIC_IP_OUT",
    "ip_pkts_in_rate": "PUBLIC_IP_PKTS_IN",
    "ip_pkts_out_rate": "PUBLIC_IP_PKTS_OUT",
    "mysql_cpu_util": "RDS_CPU",
    "mysql_memory.usage": "RDS_MEMORY",
    "mysql_volume": "RDS_VOLUME",
    "mysql_ReadIops": "RDS_IOPS_READ",
    "mysql_WriteIops": "RDS_IOPS_WRITE",
    "mysql_QPS": "RDS_QPS",
    "mysql_TPS": "RDS_TPS",
    "mysql_activeConnectionNum": "RDS_ACTIVE_CONN",
    "mysql_currentConnectionNum": "RDS_CURRENT_CONN",
    "mysql_Queries": "RDS_QUERY",
    "mysql_transCommit": "RDS_COMMIT",
    "mysql_transRollback": "RDS_ROLLBACK",
    "mysql_scanNum": "RDS_SCANNUM",
    "mysql_innodbFreeBufferSize": "RDS_FREE_BUFFER",
    "mysql_innodbBufferReadHitratio": "RDS_BUFFER_HITRATIO",
    "bandwidth_in": "LB_BANDWIDTH_IN",
    "bandwidth_out": "LB_BANDWIDTH_OUT",
    "listener_response_time": "LB_LISTENER_RESPONSE_TIME",
    "listener_concurrent_requests": "LB_LISTENER_CONCURRENT_REQUESTS",
    "listener_response_errors": "LB_LISTENER_RESPONSE_ERRORS",
    "listener_concurrent_connections": "LB_LISTENER_CONCURRENT_CONNECTIONS",
    "listener_1xx": "LB_LISTENER_1XX",
    "listener_2xx": "LB_LISTENER_2XX",
    "listener_3xx": "LB_LISTENER_3XX",
    "listener_4xx": "LB_LISTENER_4XX",
    "listener_5xx": "LB_LISTENER_5XX",
    "listener_cumulative_connections": "LB_LISTENER_CUMULATIVE_CONNECTIONS",
    "listener_cumulative_requests": "LB_LISTENER_CUMULATIVE_REQUESTS",
    "member_cumulative_connections": "LB_MEMBER_CUMULATIVE_CONNECTIONS",
    "member_response_time": "LB_MEMBER_RESPONSE_TIME",
    "member_1xx": "LB_MEMBER_1XX",
    "member_2xx": "LB_MEMBER_2XX",
    "member_3xx": "LB_MEMBER_3XX",
    "member_4xx": "LB_MEMBER_4XX",
    "member_5xx": "LB_MEMBER_5XX",
}

interval_mapper = {
    "addition_time_data": REAL_TIME_INTERVAL,
    "real_time_data": REAL_TIME_INTERVAL,
    "six_hour_data": 5 * 60,
    "one_day_data": 15 * 60,
    "two_week_data": 2 * 60 * 60,
    "one_month_data": 8 * 60 * 60
}

period_mapper = {
    "addition_time_data": REAL_TIME_INTERVAL,
    "real_time_data": (60 * REAL_TIME_INTERVAL + interval_mapper.get("real_time_data")),
    "six_hour_data": (6 * 60 * 60 + interval_mapper.get("six_hour_data")),
    "one_day_data": (24 * 60 * 60 + interval_mapper.get("one_day_data")),
    "two_week_data": (2 * 7 * 24 * 60 * 60 + interval_mapper.get("two_week_data")),
    "one_month_data": (30 * 24 * 60 * 60 + interval_mapper.get("one_month_data"))
}

standard_point_num_mapper = {
    "addition_time_data": (period_mapper.get("addition_time_data") /
                           interval_mapper.get("addition_time_data")),
    "real_time_data": (period_mapper.get("real_time_data") /
                       interval_mapper.get("real_time_data")),
    "six_hour_data": (period_mapper.get("six_hour_data") /
                      interval_mapper.get("six_hour_data")),
    "one_day_data": (period_mapper.get("one_day_data") /
                     interval_mapper.get("one_day_data")),
    "two_week_data": (period_mapper.get("two_week_data") /
                      interval_mapper.get("two_week_data")),
    "one_month_data": (period_mapper.get("one_month_data") /
                       interval_mapper.get("one_month_data")),
}

merge_item_mapper = {
    "NET_IN": "NET_IO",
    "NET_OUT": "NET_IO",
    "NET_PKTS_IN": "NET_PKTS_IO",
    "NET_PKTS_OUT": "NET_PKTS_IO",
    "SYS_DISK_READ": "SYS_DISK_RW",
    "SYS_DISK_WRITE": "SYS_DISK_RW",
    "SYS_DISK_THROUGHPUT_READ": "SYS_DISK_THROUGHPUT_RW",
    "SYS_DISK_THROUGHPUT_WRITE": "SYS_DISK_THROUGHPUT_RW",
    "DATA_DISK_READ": "DATA_DISK_RW",
    "DATA_DISK_WRITE": "DATA_DISK_RW",
    "DATA_DISK_THROUGHPUT_READ": "DATA_DISK_THROUGHPUT_RW",
    "DATA_DISK_THROUGHPUT_WRITE": "DATA_DISK_THROUGHPUT_RW",
    "ROUTER_IN": "ROUTER_IO",
    "ROUTER_OUT": "ROUTER_IO",
    "PUBLIC_IP_IN": "PUBLIC_IP_IO",
    "PUBLIC_IP_OUT": "PUBLIC_IP_IO",
    "PUBLIC_IP_PKTS_IN": "PUBLIC_IP_PKTS_IO",
    "PUBLIC_IP_PKTS_OUT": "PUBLIC_IP_PKTS_IO"
}

merge_item_prefix = [item[:item.rindex("_")] for item in merge_item_mapper.keys()]
merge_item_prefix += ["CPU_USAGE",
                      "MEMORY_USAGE",
                      # "SYS_DISK_USAGE",
                      # "DATA_DISK_USAGE"
                      ]

merge_item_mapper.update({
    "CPU_USAGE": "CPU_USAGE",
    "MEMORY_USAGE": "MEMORY_USAGE",
    # "SYS_DISK_USAGE": "SYS_DISK_USAGE",
    # "DATA_DISK_USAGE": "DATA_DISK_USAGE",
})

merge_item_prefix_set = set(merge_item_prefix)

item_to_unit = {
    "CPU_USAGE": "%",
    "MEMORY_USAGE": "%",
    # "SYS_DISK_USAGE": "%",
    # "DATA_DISK_USAGE": "%",
    # "DISK_USAGE": "%",
    "NET_IO": "KB/s",
    "NET_IN": "KB/s",
    "NET_OUT": "KB/s",
    "NET_PKTS_IO": "packet/s",
    "NET_PKTS_IN": "packet/s",
    "NET_PKTS_OUT": "packet/s",
    "SYS_DISK_RW": "transfers/s",
    "SYS_DISK_READ": "reads/s",
    "SYS_DISK_WRITE": "writes/s",
    "SYS_DISK_THROUGHPUT_RW": "KB/s",
    "SYS_DISK_THROUGHPUT_READ": "KB/s",
    "SYS_DISK_THROUGHPUT_WRITE": "KB/s",
    "DATA_DISK_RW": "transfers/s",
    "DATA_DISK_READ": "reads/s",
    "DATA_DISK_WRITE": "writes/s",
    "DATA_DISK_THROUGHPUT_RW": "KB/s",
    "DATA_DISK_THROUGHPUT_READ": "KB/s",
    "DATA_DISK_THROUGHPUT_WRITE": "KB/s",
    "DISK_READ": "reads/s",
    "DISK_WRITE": "writes/s",
    "DISK_THROUGHPUT_READ": "KB/s",
    "DISK_THROUGHPUT_WRITE": "KB/s",
    "PUBLIC_IP_IO": "KB/s",
    "PUBLIC_IP_IN": "KB/s",
    "PUBLIC_IP_OUT": "KB/s",
    "PUBLIC_IP_PKTS_IO": "packet/s",
    "PUBLIC_IP_PKTS_IN": "packet/s",
    "PUBLIC_IP_PKTS_OUT": "packet/s",
    "LB_BANDWIDTH_IN": "kbps",
    "LB_BANDWIDTH_OUT": "kbps",
    "LB_LISTENER_RESPONSE_TIME": "ms",
    "LB_LISTENER_CONCURRENT_REQUESTS": _(u"次"),
    "LB_LISTENER_RESPONSE_ERRORS": _(u"次"),
    "LB_LISTENER_CONCURRENT_CONNECTIONS": _(u"次"),
    "LB_LISTENER_1XX": _(u"次"),
    "LB_LISTENER_2XX": _(u"次"),
    "LB_LISTENER_3XX": _(u"次"),
    "LB_LISTENER_4XX": _(u"次"),
    "LB_LISTENER_5XX": _(u"次"),
    "LB_LISTENER_CUMULATIVE_CONNECTIONS": _(u"次"),
    "LB_LISTENER_CUMULATIVE_REQUESTS": _(u"次"),
    "LB_MEMBER_CUMULATIVE_CONNECTIONS": _(u"次"),
    "LB_MEMBER_RESPONSE_TIME": "ms",
    "LB_MEMBER_1XX": _(u"次"),
    "LB_MEMBER_2XX": _(u"次"),
    "LB_MEMBER_3XX": _(u"次"),
    "LB_MEMBER_4XX": _(u"次"),
    "LB_MEMBER_5XX": _(u"次")
}

item_to_display = {
    "CPU_USAGE": _(u"CPU使用率"),
    "MEMORY_USAGE": _(u"内存使用率"),
    "NET_IO": _(u"网络流量（入/出）"),
    "NET_IN": _(u"网络流量（入）"),
    "NET_OUT": _(u"网络流量（出）"),
    "NET_PKTS_IO": _(u"网络流量（入/出）包"),
    "NET_PKTS_IN": _(u"网络流量（入）包"),
    "NET_PKTS_OUT": _(u"网络流量（出）包"),
    "SYS_DISK_RW": _(u"系统盘IOPS（读/写）"),
    "SYS_DISK_READ": _(u"系统盘IOPS（读）"),
    "SYS_DISK_WRITE": _(u"系统盘IOPS（写）"),
    "SYS_DISK_THROUGHPUT_RW": _(u"系统盘吞吐量（读/写）"),
    "SYS_DISK_THROUGHPUT_READ": _(u"系统盘吞吐量（读）"),
    "SYS_DISK_THROUGHPUT_WRITE": _(u"系统盘吞吐量（写）"),
    "DATA_DISK_RW": _(u"数据盘IOPS（读/写）"),
    "DATA_DISK_READ": _(u"数据盘IOPS（读）"),
    "DATA_DISK_WRITE": _(u"数据盘IOPS（写）"),
    "DATA_DISK_THROUGHPUT_RW": _(u"数据盘吞吐量（读/写）"),
    "DATA_DISK_THROUGHPUT_READ": _(u"数据盘吞吐量（读）"),
    "DATA_DISK_THROUGHPUT_WRITE": _(u"数据盘吞吐量（写）"),
    "PUBLIC_IP_IO": _(u"公网IP（入/出）"),
    "PUBLIC_IP_IN": _(u"公网IP（入）"),
    "PUBLIC_IP_OUT": _(u"公网IP（出）"),
    "PUBLIC_IP_PKTS_IO": _(u"公网IP（入/出）包"),
    "PUBLIC_IP_PKTS_IN": _(u"公网IP（入）包"),
    "PUBLIC_IP_PKTS_OUT": _(u"公网IP（出）包"),
    "RDS_CPU": _(u"CPU使用率"),
    "RDS_MEMORY": _(u"内存使用率"),
    "RDS_VOLUME": _(u"数据盘使用率"),
    "RDS_IOPS_READ": _(u"读IOPS"),
    "RDS_IOPS_WRITE": _(u"写IOPS"),
    "RDS_QPS": _(u"每秒SQL数"),
    "RDS_TPS": _(u"每秒事务数"),
    "RDS_ACTIVE_CONN": _(u"活跃连接数"),
    "RDS_CURRENT_CONN": _(u"当前连接数"),
    "RDS_QUERY": _(u"query请求数"),
    "RDS_COMMIT": _(u"提交事务数"),
    "RDS_ROLLBACK": _(u"回滚事务数"),
    "RDS_SCANNUM": _(u"扫描全表数"),
    "RDS_FREE_BUFFER": _(u"空闲缓冲池"),
    "RDS_BUFFER_HITRATIO": _(u"缓冲池命中率"),
    "LB_BANDWIDTH_IN": _(u"服务带宽（入）"),
    "LB_BANDWIDTH_OUT": _(u"服务带宽（出）"),
    "LB_LISTENER_RESPONSE_TIME": _(u"后端服务响应时延"),
    "LB_LISTENER_CONCURRENT_REQUESTS": _(u"并发请求数"),
    "LB_LISTENER_RESPONSE_ERRORS": _(u"后端服务错误响应数"),
    "LB_LISTENER_CONCURRENT_CONNECTIONS": _(u"并发连接数"),
    "LB_LISTENER_1XX": _(u"1XX响应次数"),
    "LB_LISTENER_2XX": _(u"2XX响应次数"),
    "LB_LISTENER_3XX": _(u"3XX响应次数"),
    "LB_LISTENER_4XX": _(u"4XX响应次数"),
    "LB_LISTENER_5XX": _(u"5XX响应次数"),
    "LB_LISTENER_CUMULATIVE_CONNECTIONS": _(u"累计连接数"),
    "LB_LISTENER_CUMULATIVE_REQUESTS": _(u"累计请求数"),
    "LB_MEMBER_CUMULATIVE_CONNECTIONS": _(u"并发连接数"),
    "LB_MEMBER_RESPONSE_TIME": _(u"响应时延"),
    "LB_MEMBER_1XX": _(u"1XX响应次数"),
    "LB_MEMBER_2XX": _(u"2XX响应次数"),
    "LB_MEMBER_3XX": _(u"3XX响应次数"),
    "LB_MEMBER_4XX": _(u"4XX响应次数"),
    "LB_MEMBER_5XX": _(u"5XX响应次数")
}


# period_point_mapper = {
#     "addition_time_data": 1,
#     "real_time_data": 12,
#     "six_hour_data": 12,
#     "one_day_data": 12,
#     "two_week_data": 14,
#     "one_month_data": 15
# }
